load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
   name = "rules_foreign_cc",
   strip_prefix = "rules_foreign_cc-master",
   url = "https://github.com/bazelbuild/rules_foreign_cc/archive/master.zip",
)

load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")

all_content = """filegroup(name = "all", srcs = glob(["**"]), visibility = ["//visibility:public"])"""
http_archive(
    name = "bison",
    build_file_content = all_content,
    strip_prefix = "bison-3.3",
    urls = ["http://ftp.gnu.org/gnu/bison/bison-3.3.tar.gz"],
)

http_archive(
    name = "flex",
    build_file_content = all_content,
    strip_prefix = "flex-2.6.4",
    urls = ["https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz"],
)

rules_foreign_cc_dependencies()

